### ISSUE TITLE
error msmc2 :estimating population separation history

### ISSUE THREAD

**Issue by ncnlll** [stschiff/msmc2#21]
Hi,
I want to estimate population separation history between two populations but when i run 
"msmc2 -t 2 -I 0-6,0-7 -s -p 1*2+15*1+1*2 -o $OUTDIR/king_emperor.msmc2 $INPUTDIR/input.multihetsep.txt" I get this error:
??:? double[] powell.Powell!(maximization_step.MinFunc).Powell.minimize(double[], double[][]) [0x56f836]
??:? double[] powell.Powell!(maximization_step.MinFunc).Powell.minimize(double[]) [0x56f3c7]
??:? model.psmc_model.PSMCmodel maximization_step.getMaximization(double[][], double[][2], model.psmc_model.PSMCmodel, const(ulong[]), bool) [0x570fdd]
??:? void msmc2.run() [0x5741e2]
??:? _Dmain [0x5728fc]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5cbc56]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5cbbac]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5cbc12]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5cbbac]
??:? _d_run_main [0x5cbb09]
??:? main [0x57bbc5]
??:? __libc_start_main [0x69851ec4]

Can you give me some help?
Thank you
Lorena

**Comment by stschiff** [comment]
Please send me the input file.

**Comment by ncnlll** [comment]
Just sent it to schiffels@shh.mpg.de
Thank you 
Lorena

**Comment by stschiff** [comment]
OK, I tried it, and can report that MSMC2 indeed throws an error after the 5th loop, with the key error message `powell exceeding maximum iterations`. You didn't post that message in your problem description above, so please check and confirm. If that is the case, it means that there is some issue related to overfitting, which in my experience happens in particular if there is relatively too little data for the parameters you're testing. 

Please try to use even fewer parameters than what you've put. So instead of `-p 1*2+15*1+1*2`, try `-p 5*1` or so... that won't help you, but at least you can see whether it finishes and work from there to try finer intervals. Having said that, you may simply not have enough data here. Was there just a single chromosome? Is that all the data you have?

**Comment by ncnlll** [comment]
Hi Stephan,
yes i have the key error message "powell exceeding maximum iterations",  I forgot to post the first part of the error, sorry. 
Our dataset consists of the entire genome of 4 penguin species but divided into scaffolds and I'm trying to test msmc2 on a single scaffold at a time with 6 individuals of 2 different species.
I tried with  -p 5*1 but i get the same error after the 6th loop, with -p 4*1 it works but i get a strange plot with a relative cross-coalescence rate greater than 1.
![cross png](https://user-images.githubusercontent.com/48827031/57644451-67f63180-75bc-11e9-8bae-366c8ff045be.PNG)

And also when i plot the effective population size I get population sizes that are too large.
![effectivepopsize](https://user-images.githubusercontent.com/48827031/57645005-a2ac9980-75bd-11e9-8359-5651e7b641c5.png)

Thanks for your help.
Lorena

**Comment by stschiff** [comment]
Please try to run on all the data you have. I’m aware that MSMC2’s behaviour with respect to this error isn’t the most useful. I can only say that this literally never happens with human-scale data, so it must have to do with simply too little data. There are weird runaway-effects happening in the numerics that cause these issues in the Maximization step of the algorithm.

**Comment by ncnlll** [comment]
Thank you Stephan, I will try with all the data.
Lorena
