### ISSUE TITLE
Problems when install the msmc2

### ISSUE THREAD

**Issue by 7melo7** [stschiff/msmc2#33]
Hello, Professor

I have installed the GSL and DMD.
but when i install the msmc2 by typeing the `make` command

dmd -O /public1/home/guowl/software/gsl-2.7/lib/libgsl.a /public1/home/guowl/software/gsl-2.7/lib/libgslcblas.a -odbuild/test -ofbuild/release/msmc2 model/transition_rate.d model/stateVecAllocator.d model/gsl_matrix_vector.d model/psmc_hmm.d model/propagation_core.d model/time_intervals.d model/psmc_model.d model/stateVec.d model/data.d powell.d brent.d maximization_step.d expectation_step.d msmc2.d logger.d
make: dmd: Command not found
make: *** [build/release/msmc2] Error 127

but i have added the dmd bin directory into the environment PATH.

Is there something I'm missing? Would be grateful for any assistance here.

Thank you,

**Comment by stschiff** [comment]
`dmd: Command not found`: Not something I can support sorry. You clearly don't have `dmd` on your path.

**Comment by 5681** [comment]
Dear Stephan,

I'm trying to install msmc2 and running into problems. I believe I correctly installed GSL library and DMD, which is activated.

The make command I run (within the msmc2-2.1.3 directory) gives me the following error:
**(dmd-2.100.0)Boni@Marias-MBP msmc2-2.1.3 % make
dmd -O /usr/local/lib/libgsl.a /usr/local/lib/libgslcblas.a -odbuild/test -ofbuild/release/msmc2 model/data.d model/gsl_matrix_vector.d model/propagation_core.d model/psmc_hmm.d model/psmc_model.d model/stateVec.d model/stateVecAllocator.d model/time_intervals.d model/transition_rate.d powell.d brent.d maximization_step.d expectation_step.d msmc2.d logger.d
model/propagation_core.d(129): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
model/propagation_core.d(142): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
model/propagation_core.d(156): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
model/propagation_core.d(174): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
model/propagation_core.d(226): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
model/psmc_hmm.d(122): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
model/psmc_hmm.d(188): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
model/psmc_hmm.d(204): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
model/psmc_hmm.d(240): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
model/psmc_hmm.d(258): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
model/time_intervals.d(99): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
model/time_intervals.d(110): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
model/time_intervals.d(127): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
model/transition_rate.d(103): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
model/transition_rate.d(122): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
maximization_step.d(152): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
maximization_step.d(163): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
maximization_step.d(183): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
maximization_step.d(201): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
clang: error: no such file or directory: '/usr/local/lib/libgsl.a'
clang: error: no such file or directory: '/usr/local/lib/libgslcblas.a'
Error: linker exited with status 1
make: *** [build/release/msmc2] Error 1
(dmd-2.100.0)Boni@Marias-MBP msmc2-2.1.3 % pwd**

I then edited the Makefile as follows to indicates where I installed the gsl libraries:
**# Set this variable to your static gsl libraries
GSLDIR=/Users/Boni/Dropbox/SENCKENBERG/wild_cat_project/msmc/gsl/gsl-2.7.1
GSL=${GSLDIR}/libgsl.a ${GSLDIR}/libgslcblas.a**

However, the problem is still not solved:
**maximization_step.d(201): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
clang: error: no such file or directory: '/Users/Boni/Dropbox/SENCKENBERG/wild_cat_project/msmc/gsl/gsl-2.7.1/libgsl.a'
clang: error: no such file or directory: '/Users/Boni/Dropbox/SENCKENBERG/wild_cat_project/msmc/gsl/gsl-2.7.1/libgslcblas.a'
Error: linker exited with status 1
make: *** [build/release/msmc2] Error 1**

Any ideas how I could tackle this?

Best regards
ME

**Comment by stschiff** [comment]
Goodness. OK. Thanks for reporting. It seems I need to upgrade to the latest DMD versions. I'm on vacation the next two weeks and will likely take care of this only then. Sorry. Have you tried one of the precompiled executables in [release](https://github.com/stschiff/msmc2/releases)?

**Comment by 5681** [comment]
Dear Stephan,

I have tried now the executable msmc2_linux64bit and it seems to work.

Best regards

ME

**Comment by stschiff** [comment]
Latest release v2.1.4 compiles with new D compilers.
